defmodule AtomicRepro.Repo.Migrations.Initial do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:atomics, primary_key: false) do
      add :id, :bigserial, null: false, primary_key: true
      add :approved, :boolean
      add :state, :text, null: false, default: "initialized"
    end
  end

  def down do
    drop table(:atomics)
  end
end
